Release/0.1.2
mskcc-omics-workflows/modules pull request #156
Opened 2024-11-01 16:16 UTC by buehlere

release 0.1.2

2024-11-01 16:55 UTC, nikhil requested changes

2024-11-01 16:55 UTC, nikhil commented on modules/msk/genomenexus/annotationpipeline/main.nf
> -    java -Xms${task.memory.toMega()/4}m -Xmx${task.memory.toGiga()}g -jar /genome-nexus-annotation-pipeline/annotationPipeline/target/annotationPipeline.jar --filename ${input_maf} --output-filename
This looks like a regression. I remember we added the java args for a bug fix. Also, it is moving the image version from 1.05 to 1.0.4

2024-11-26 15:07 UTC, nikhil requested changes

2024-11-26 15:07 UTC, nikhil commented on modules/msk/genomenexus/annotationpipeline/main.nf
> -        genomenexus: 'annotation pipeline version 1.0.5'
Not sure why the version is going down here

2024-11-26 22:36 UTC, rhshah commented on .github/CODEOWNERS
> +./modules/msk/gatk4/applybqsr/** @yocra3 @FriederikeHanssen @mskcc-omics-workflows/reviewers
Just fyi we need to fix the meta yaml files here  by removing these users: @yocra3 @FriederikeHans

2024-11-26 22:36 UTC, rhshah commented on .github/CODEOWNERS
> +./modules/msk/salmon/index/** @kevinmenden @drpatelh @nikhil @mskcc-omics-workflows/reviewers
Again we need to fix the meta yaml files here  by removing these users: @kevinmenden @drpatelh

2024-11-27 15:20 UTC, rhshah approved these changes

2024-11-27 15:43 UTC, nikhil approved these changes

2024-11-27 15:45 UTC, merged