Feature/getbasecountmulti
mskcc-omics-workflows/modules pull request #25
Opened 2022-11-01 13:43 UTC by buehlere

✔️ add module for getbasecount: https://github.com/msk-access/GetBaseCountsMultiSample 
✔️ create test data set and tests
✔️ add testing config to repo so gui selection of testing environment works correctly: https://github.com/mskcc-omics-workflows/tools/blob/6164ed6ee163bfd4c0c11ca389a0ee971327587a/tests/config/nextflow.config

2022-11-07 15:08 UTC, huyu335 requested changes
There are some conflicts comparing to master branch. Can we please resolve them? Thanks!

2022-11-07 15:08 UTC, huyu335 commented on tests/modules/msk-tools/getbasecountmultisample/main.nf
> +        [args: '--omaf']
If this arg is always associated with either maf or vcf, maybe we can just put it in the main script, instead of parsing it as an input?

2022-11-15 19:14 UTC, buehlere commented on tests/modules/msk-tools/getbasecountmultisample/test.yml
> +- name: msk-tools getbasecountmultisample test_getbasecountmultisample_maf
I may need some help getting the hpc testing working.

2022-11-15 19:15 UTC, buehlere commented on modules/msk-tools/getbasecountmultisample/meta.yml
> +name: "getbasecountmultisample"
Updated documentation!

2022-11-15 19:16 UTC, buehlere commented on tests/modules/msk-tools/getbasecountmultisample/main.nf
> +include { GETBASECOUNTMULTISAMPLE as GETBASECOUNTMULTISAMPLE_VCF} from '../../../../modules/msk-tools/getbasecountmultisample/main.nf'
Now only import once.

2022-11-15 19:16 UTC, buehlere commented on modules/msk-tools/getbasecountmultisample/main.nf
> +     path('test.{vcf,maf}')
changed name to be slightly more descriptive: `variant_file`

2022-11-15 19:22 UTC, buehlere commented on tests/modules/msk-tools/getbasecountmultisample/main.nf
> +        [args: '--omaf']
I'm not sure we want this as a required argument? I believe the default is to output a vcf not maf, so I'm not sure it's always associated with a vcf or maf input? Or at least the behavior is as follows:
- getbasecountmultisample with vcf, bam  --outputs-> vcf  
- getbasecountmultisample with vcf, bam  --outputs-> vcf  
- getbasecountmultisample with vcf, bam and --omaf flag --outputs-> maf 
- getbasecountmultisample with maf, bam and --omaf flag --outputs-> maf 

In nf-core's fgbio documentation they suggest passing optional arguments as a groovy map: https://nf-co.re/docs/contributing/tutorials/dsl2_modules_tutorial.

2022-11-15 19:23 UTC, buehlere commented
Hi @huyu335, just responded to your review. Let me know how things look!

2022-11-15 19:25 UTC, buehlere commented on modules/msk-tools/getbasecountmultisample/main.nf
> +    container "ghcr.io/msk-access/gbcms:1.2.5"
Sounds good. I've included the dockerfile at the very least. Is the plan to upload the containers to this group?

2022-11-18 17:48 UTC, huyu335 commented on modules/msk-tools/getbasecountmultisample/main.nf
> +    container "ghcr.io/msk-access/gbcms:1.2.5"
That would be great to put them together for better management.

2022-11-18 20:28 UTC, buehlere commented on tests/modules/msk-tools/getbasecountmultisample/test.yml
> +- name: msk-tools getbasecountmultisample test_getbasecountmultisample_maf
I've added the update we worked on today.

2022-11-18 20:28 UTC, buehlere commented on modules/msk-tools/getbasecountmultisample/main.nf
> +    container "ghcr.io/msk-access/gbcms:1.2.5"
uploaded the image and changed the pull!

2022-11-26 16:09 UTC, huyu335 approved these changes

2022-11-26 16:09 UTC, merged