Msisensor-ct
mskcc-omics-workflows/modules pull request #7
Opened 2023-10-16 17:43 UTC by carmelinacharalambous

### currently testing ###

2023-10-18 19:08 UTC, buehlere requested changes
Feel free to reach out with any questions. I tried to summarize what we went over.

2023-10-18 19:08 UTC, buehlere commented on tests/modules/msk/msisensor-ct/main.nf
> +include { MSISENSOR-CT } from '../../../../modules/msk/msisensor-ct/scan/main.nf'
Split these into two test for msi and scan. Correct include to correct name MSISENSOR-CT-MSI and MSISENSOR-CT-SCAN

2023-10-18 19:08 UTC, buehlere commented on tests/modules/msk/msisensor-ct/main.nf
> +    input = [
input for empty test

2023-10-18 19:08 UTC, buehlere commented on tests/modules/msk/msisensor-ct/main.nf
> +workflow test_msisensor_ct_data {
input for test with data on juno. This test is similar to how you'd run an actual workflow using your module.

2023-10-18 19:08 UTC, buehlere commented on tests/modules/msk/msisensor-ct/nextflow.config
> +process {
you can add optional parameters here with: `withName <module> { ext.args = '< option1 > < option2 >'} `

2023-10-18 19:08 UTC, buehlere commented on modules/msk/msisensor-ct/scan/main.nf
> +}
add stub test here. See here: https://github.com/mskcc-omics-workflows/modules/blob/73b78e1dfa2121a120b8c681162525d428ef8bb7/modules/msk/gbcms/main.nf#L40-L47. We're faking the output files for the empty run of the module that we do here: https://github.com/mskcc-omics-workflows/modules/blob/73b78e1dfa2121a120b8c681162525d428ef8bb7/tests/modules/msk/gbcms/main.nf#L7-L24

2023-10-18 19:08 UTC, buehlere commented on modules/msk/msisensor-ct/scan/main.nf
> +    input:
you can add parameters here.

2023-10-18 19:08 UTC, buehlere commented on modules/msk/msisensor-ct/scan/main.nf
> +    def args = task.ext.args ?: ''
edit the parameters here.

2023-10-18 19:08 UTC, buehlere commented on modules/msk/msisensor-ct/scan/main.nf
> +        -d $fasta \\
add them to the command here.

2023-10-18 19:08 UTC, buehlere commented on tests/modules/msk/msisensor-ct/test.yml
> +  command: nextflow run ./tests/modules/msk/msisensor-ct -entry test_msisensor_ct -c ./tests/config/nextflow.config -c ./tests/modules/msk/msisensor-ct/nextflow.config -stub-run
This is the command to actually run the stubtest. You can run this in your terminal to see if everything is working. Don't worry about the pytest for right now. Feel free to reach out if get an error.

If you want to run your 'real data test', you can change the `-entry` to another test name and remove `-stub-run`.

2024-02-05 18:26 UTC, rhshah commented
@carmelinacharalambous  I know this is something we are not pursuing do you want to close this?

2024-02-05 18:53 UTC, closed without merging

2024-02-05 18:53 UTC, carmelinacharalambous commented
PR will be closed as we are no longer pursuing MSIsensor-ct